### ISSUE TITLE
bubbled event: detail 

### ISSUE THREAD

**Issue by dasher** [PolymerElements/paper-dialog-behavior#11]
Raising this issue here although the underlying problem is with iron-overlay-behavior as the documentation is on this element.

A button clicked containing the dialog-dismiss attribute doesn't properly set the canceled property on the event object passed bubbled event.

Additionally the passed event has detail property {confirmed: boolean, canceled: boolean} rather than a property suggested in the documentation called closingReason

**Comment by morethanreal** [comment]
This behavior is intentional. `canceled` implies that the user dismissed the dialog by pressing escape or clicking outside the dialog, instead of interacting with the dialog. If the user closes the dialog by clicking a `<paper-button dialog-dismiss>`, it is considered closing. Documentation here: https://elements.polymer-project.org/elements/iron-overlay-behavior?active=Polymer.IronOverlayBehavior

The event detail is set to the `closingReason` object which has the `confirmed` and `canceled` properties. It seems like the doc for the param isn't showing up for some reason - fixing in https://github.com/PolymerElements/iron-overlay-behavior/pull/17

**Comment by valdrinkoshi** [comment]
closing this as PR got merged
