### ISSUE TITLE
paper-dialog-scrollable automatically scrolls to top when the content changes

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/paper-dialog-behavior#73]
_From @kungufli on February 23, 2016 11:17_

`paper-dialog-scrollable` scrolls automatically to top when the content changes. I think this is an unwanted behavior. Here there is an example: scroll all down and click on the last item (Item 8):
http://jsbin.com/nuyeyotoma/edit?html,output

_Copied from original issue: PolymerElements/paper-dialog-scrollable#39_

**Comment by valdrinkoshi** [comment]
Yeah, `iron-collapse` will fire `iron-resize` at the end of the animation, and `iron-overlay-behavior` listens to it and calls `refit` if opened.

I'm not sure this can be solved in `paper-dialog-scrollable` itself, because in this case is the container that causes the `refit`, so it's the container's responsibility to keep track of the scrollTop.
Probably this should be done in `paper-dialog`

In the meantime this should help you :) http://jsbin.com/pipelo/1/edit?html,output

**Comment by kungufli** [comment]
@valdrinkoshi thanks for the help, this is just what I need to workaround the issue until it won't be fixed.

**Comment by cnbuff410** [comment]
@kungufli  I tried the way in the jsbin link but I'm not sure how it works within a Polymer component.

say I have a 

<paper-dialog-scrollable id="myScroll"></paper-dialog-scrollable>

_myScroll.$.scrollable.scrollTop = scrollTop;_ can not pass the compilation, I also tried 

_Plymer.dom(this.$.myScroll).$.scrollable.scrollTop = scrollTop_

or things like this but none of them work. I tried to change scrollTop to be other big values (1000 or so), still no luck.

Can I have a more clear path on how to have a workaround for this issue? Thanks!

**Comment by kungufli** [comment]
@cnbuff410 the workaround suggested by @valdrinkoshi has worked until some time ago, but now I can confirm it's broken with the latest versions of the elments involved. It seems that the `scrollTop` property of the scrollable element is reset to 0 after the `iron-resize` call. A possible solution is to set the correct value in a timeout, but this is really ugly and make a very anti-material design effect (that will make Matias Duarte crying, I suppose) where the scroll first go to top and than go back to the correct point. However here is a working example, just in case: http://jsbin.com/wicezesado/1/edit?html,output

I have to say I'm very disappointed that this bug was not already properly fixed by te Polymer team.

**Comment by valdrinkoshi** [comment]
The reason this doesn't work is because `iron-overlay-behavior` uses `requestAnimationFrame` to call `refit` on `iron-resize`, hence refit gets called **after** our listener and the scrollTop gets reset.
I think the proper place to fix this is in `iron-fit-behavior`, which should try to preserve the `scrollTop` and `scrollLeft` of the `sizingTarget`. Will try to fix it there.

**Comment by kungufli** [comment]
@valdrinkoshi Many many Thanks for having fixed the issue.
