### ISSUE TITLE
Many API properties are double negatives (i.e. noDoSomething: true instead of doSomething: false)

### ISSUE THREAD

**Issue by danbeam** [PolymerElements/paper-dialog-behavior#80]
why does `PaperDialogBehavior` have 3 double negative properties?  so defaults can be `false`?

```javascript
properties: {
  autoFocus: true,
  cancelOnEscKey: true,
  cancelOnOutsideClick: true,
}
```

seems way less clear than:

```javascript
properties: {
  noAutoFocus: false,
  noCancelOnEscKey: false,
  noCancelOnOutsideClick: false,
}
```

to me.

I am noticing this in response to: https://codereview.chromium.org/1822813002/

/cc @freshp86 @valdrinkoshi @notwaldorf @tjsavage

**Comment by valdrinkoshi** [comment]
These properties are inherited from `iron-overlay-behavior`, so this issue should be moved there.
Answering the question: the double negative is due to the fact that boolean properties in Polymer will be considered true just by checking the **presence** of the attribute, and not the value. Extract from the [doc](https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-deserialization):
> Boolean properties are set based on the presence of the attribute: if the attribute exists at all, the property is set to true, regardless of the attribute value. If the attribute is absent, the property gets its default value.

So, imagine we'd set `autoFocus` with default `true`. In order to disable it, the Polymer user would have to do it imperatively through javascript, but wouldn't be able to do this by setting attributes.

**Comment by danbeam** [comment]
ah, it's to match boolean attributes in HTML.  i understand.  bummer.

http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes
