### ISSUE TITLE
dialog-dismiss does not fire iron-overlay-canceled

### ISSUE THREAD

**Issue by jscissr** [PolymerElements/paper-dialog-behavior#90]
Is it intentional that a cancel button (with `iron-dismiss`) does not fire `iron-overlay-canceled`, while clicking outside the dialog or pressing ESC does? It seems a bit strange to me that they are treated differently.

If this is something that should be fixed, I'd send a pull request.

**Comment by valdrinkoshi** [comment]
Hi @jscissr, that is the expected behavior; `iron-overlay-canceled` is fired when the user either clicks outside the overlay or presses the ESC key. You have a chance to prevent the closing by calling `event.preventDefault` in that case.
If a dialog gets closed by clicking on elements with attribute `dialog-dismiss` or `dialog-confirm` will update the `closingReason.confirmed` (which is the `event.detail` of `iron-overlay-closed`).
See the documentation of [`paper-dialog-behavior`](https://elements.polymer-project.org/elements/paper-dialog-behavior) and [`iron-overlay-behavior`](https://elements.polymer-project.org/elements/iron-overlay-behavior) for more details.
